### ISSUE TITLE
vue version mismatch

### ISSUE THREAD

**Issue by EnterpriseWide** [niccord/nuxt-stripe-shop#1]
Hey there,
When i run the command
npm run dev

I get the following:
  Vue packages version mismatch:

  - vue@2.5.17
  - vue-server-renderer@2.6.12

Can you have a look?

**Comment by niccord** [comment]
Hi,
this project was created for test purposes and abandoned pretty soon.

Anyway, have you tried installing the packages via `npm ci`?

**Comment by ben-norman-teetotaler** [comment]
:( I'm sorry it was abandoned. It is perfect for what I am after.
I did the following
npm install
npm run dev

does it work for you when you do it, does it?

**Comment by niccord** [comment]
As I said, have you tried with `npm ci` instead of `npm install` on the first step?

**Comment by niccord** [comment]
Hi,
I have updated the libraries versions so the error is no longer happening.

Cheers!
